title: Default Page
icon: page

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          pageBuilder:
            label: Page Builder
            type: blocks
            fieldsets:
              text:
                label: Text
                type: group
                fieldsets:
                  - heading
                  - text

              media:
                label: Media
                type: group
                fieldsets:
                  - image
                  - video

              custom:
                label: Custom Modules
                type: group
                fieldsets:
                  hero: blocks/hero
                  teaser: blocks/teaser

  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default

      files:
        type: files
